name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the form below to help us understand and fix the issue.
        
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: When I run `iptvportal sql -q "SELECT * FROM media"`, I get an error...
    validations:
      required: true
      
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: The query should return results from the media table...
    validations:
      required: true
      
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened? Include any error messages.
      placeholder: |
        Error: Connection timeout
        Traceback...
    validations:
      required: true
      
  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Provide detailed steps to reproduce the issue.
      placeholder: |
        1. Install iptvportal-client
        2. Run `iptvportal config init`
        3. Run `iptvportal auth`
        4. Run `iptvportal sql -q "SELECT * FROM media"`
        5. See error
    validations:
      required: true
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      multiple: true
      options:
        - CLI
        - Client (sync/async)
        - Transpiler (SQL to JSONSQL)
        - Authentication
        - Schema mapping
        - Sync/Cache
        - Configuration
        - Documentation
        - Other
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: Version
      description: What version of iptvportal-client are you using?
      placeholder: "0.1.0"
    validations:
      required: true
      
  - type: input
    id: python
    attributes:
      label: Python Version
      description: What version of Python are you using?
      placeholder: "3.12.0"
    validations:
      required: true
      
  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Provide details about your environment
      placeholder: |
        OS: Ubuntu 22.04
        Installation method: pip/uv
        Virtual environment: yes/no
    validations:
      required: false
      
  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs
      description: Include relevant logs (run with `--debug` flag for detailed output)
      render: shell
      placeholder: |
        $ iptvportal sql -q "SELECT * FROM media" --debug
        [DEBUG] ...
    validations:
      required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
    validations:
      required: false
