name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please describe your idea in detail below.
        
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I'd like to be able to...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
    validations:
      required: false
      
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      multiple: true
      options:
        - CLI
        - Client (sync/async)
        - Transpiler (SQL to JSONSQL)
        - Authentication
        - Schema mapping
        - Sync/Cache
        - Configuration
        - Documentation
        - Other
    validations:
      required: true
      
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical - Blocking my work
        - High - Significantly impacts workflow
        - Medium - Would be nice to have
        - Low - Minor improvement
    validations:
      required: true
      
  - type: textarea
    id: examples
    attributes:
      label: Usage Examples
      description: Provide examples of how this feature would be used
      placeholder: |
        # Example 1
        $ iptvportal sql -q "SELECT * FROM media" --export-csv output.csv
        
        # Example 2
        from iptvportal import Client
        client.export_to_csv("output.csv")
    validations:
      required: false
      
  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how to implement this, share them here
      placeholder: |
        Could modify src/iptvportal/cli/commands/sql.py to add --export-csv flag...
    validations:
      required: false
      
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be interested in contributing this feature?
      options:
        - label: I'm willing to implement this feature
          required: false
        - label: I can help with testing
          required: false
        - label: I can help with documentation
          required: false
      
  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request
    validations:
      required: false
